sirocco-ventures/raggenie

CONTRIBUTING.md, README.md
Added invite link to slack group in communities. Connected broken links in readme and contributions. Added placeholder for running raggenie using docker for current implimentation.
=> Updated Readme Links and Added Communities Section

config.yaml, requirements.txt, ui/package-lock.json, ui/src/pages/Configuration/ProviderForm/ProviderForm.jsx, ui/src/pages/Configuration/ProviderForm/ProviderForm.module.css, ui/yarn.lock
**Add placeholder and hint for URL input box on Website Plugin Configuaration Page**
**ISSUE 29**
**Changes Made**
1-) **Added placeholder to URL input box**
2-) **Included a Hint below the input box**
3-)**removed uvloop from requirements.txt **
Please Review !
=> Add placeholder and hint for URL input box on Website Plugin Configuaration Page

config.yaml, ui/src/pages/ChatConfiguration/ChatConfiguration.jsx, ui/src/utils/http/Request.js
Handled error if the API response has a status key with a value of false #42
=> Handle error if the API response contains a status value of false

app/api/v1/main_router.py
Closes #65
Loom Link for the update:
https://www.loom.com/share/8c4197b6e3754fb58801015031df2b23?sid=33d88666-80b9-480a-bf36-13707b777a57
=> Made the output response JSON serializable before saving it into the chat_histories table

app/base/base_llm.py, app/base/model_loader.py, app/loaders/ai71/loader.py, app/loaders/openai/loader.py, app/loaders/togethor/loader.py
=> updated Ai71 loader response format

app/plugins/bigquery/handler.py
=> Update Bigquery plugin health check by querying schema info from available datasets

README.md
Added steps to run frontend component to the readme.
=> Updated readme to include steps to run frontend components

README.md
Include a Demo video of RAGGENIE on ReadMe
=> Add Demo Video on read me

app/api/v1/connector.py, app/chain/chains/intent_chain.py, app/chain/modules/intent_extracter.py, app/chain/modules/metadata_generator.py, app/chain/modules/router.py, app/main.py, app/providers/container.py, app/services/connector.py
1. **Fixed Bug**: Resolved an issue where the connector health check was causing application failures.
2. **Refactored Code**: Updated the container implementation to use `Callable` instead of `Singleton`, which stops configuration caching.
3. **Intent Clarification**: Clarified that the `metadata_enquiry` intent is now only used when database connectors are available, ensuring correct functionality.
4. **Prompt Update**: Enhanced the prompt for the metadata generator for better usability.
=> Fix Connector Health Check Bug and Update Metadata Generator

ui/src/pages/Preview/ChatBox.jsx
Fixes #48 
Updated test description
=> Updated chatbot inference message

ui/src/pages/ChatConfiguration/ChatConfiguration.jsx
**API KEY input made of password type **
Please review !
=> API KEY input made of password type

app/plugins/postgresql/__init__.py, app/plugins/postgresql/formatter.py
=> Added visualization type (pie, bar and line chart) for postgreSQL plugin

ui/src/components/ChatBox/ChatBox.jsx, ui/src/components/ChatBox/ChatBox.module.css, ui/src/pages/Preview/ChatBox.jsx
This pull request addresses several key issues related to the chat history feature:
- **Fixed Chat History Loading Issue**: Resolved the problem where the chat history did not load when clicking the "chat history" button.
- **Enhanced Send Button Functionality:** Added functionality to the send button to ensure messages are sent smoothly and reliably.
- **UI Glitch Fix**: Corrected the UI glitch that occurred when switching between different chat histories, improving overall user experience.
=> Resolve chat history loading issue

.dockerignore, Dockerfile
This was my first time using Docker, so take that as a warning, but I think I'm done.
Couldn't get onnxruntime to work with Alpine-based images, so I used Bookworm.
=> Add Dockerfile for Backend App to Build and Run in Python

app/chain/modules/generator.py, app/chain/modules/ouput_formatter.py, app/plugins/document/__init__.py, app/utils/parser.py
=> Fixed Application Crashes When Querying JSON from YAML

ui/src/components/ChatBox/ChatBox.module.css, ui/src/components/ChatBox/Message.jsx, ui/src/components/ChatBox/Summary.jsx, ui/src/components/ChatBox/Time.jsx, ui/src/components/ChatBox/assets/query-close.svg, ui/src/components/ChatBox/assets/query-open.svg, ui/src/components/ChatBox/assets/summary-down.svg, ui/src/components/ChatBox/assets/summary-up.svg
Enhanced the chat summary UI to include a data summary and SQL query functionality. Sample screenshots are attached below
=> Enhance chat summary UI

ui/src/pages/Configuration/ProviderForm/ProviderForm.jsx
**PR Description:**
- Modified the behavior of the "Save and Continue" button and the "Test Connection" button in the ProviderForm component.
- The "Save" button is now disabled if any changes are made to the form after a successful test.
- The "Test Connection" button is re-enabled when any modifications are detected, ensuring that users re-test the credentials before saving.
**Affected File:**
- `raggenie/ui/src/pages/Configuration/ProviderForm/ProviderForm.jsx`
**ScreenShot / Video**
https://www.loom.com/share/3abacd24663746058fcf78dfe5f180c4?sid=acdd0191-9abd-4a55-9a62-526362db78df
=> Fix: Disable "Save" Button and Re-enable "Test Connection" on Form Changes in ProviderForm

docker-compose.yml, ui/Dockerfile
Add Docker Compose for running front- and back-end After running "docker-compose up --build" the app should be available on localhost:8080
=> Add docker-compose-yml

app/api/v1/auth.py, app/providers/config.py, app/providers/middleware.py, ui/src/layouts/dashboard/Dashboard.jsx, ui/src/layouts/dashboard/SideMenu.jsx, ui/src/routes/MainRoute.jsx, ui/src/store/authStore.js
- Fixed Login redirection if Auth is disabled
- Added default username for user
- Fixed middleware 401 error
=> Fixed Auth Issue

README.md, app/chain/modules/intent_extracter.py, ui/src/pages/ChatConfiguration/ChatConfigurationForm.jsx, ui/src/pages/Preview/Preview.jsx
- Added a CSS class `LLMDropdownOptionImg` to the `<img>` tag within the LLM dropdown options.
- Fixed string formatting in `intent_extracter.py` by replacing double quotes with single
quotes inside f-strings to prevent syntax errors.
- Adjusted the height calculation in `Preview.jsx` from `calc(100vh - 68px)` to `calc(100vh
76px)` to improve UI layout and ensure proper rendering of the `DashboardBody` component.
- README.md                                                                                                                                                                               
• Added new LLM providers: Ollama and AI71.                                                                                                                                            
• …
=> Fix LLM dropdown styling in ChatConfigurationForm and update readme.md
